# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
# Default configuration for extension with alias: "fos_rest"
fos_rest:
  param_fetcher_listener:
    enabled:             true
  cache_dir:            '%kernel.cache_dir%/fos_rest'
  routing_loader:       false
  body_converter:
    enabled:              true
  serializer:
    serialize_null:       true
  view:
    view_response_listener:
      enabled:              true
  body_listener:
    enabled:              false
  format_listener:
    enabled:              true
    rules:
      -
        path:                 ^/api
        prefer_extension:     false
        fallback_format:      json
        priorities:           [json]
      -
        path:                 ^/
        prefer_extension:     true
        fallback_format:      html
        priorities:           [ 'html', '*/*']
